#!/usr/bin/env bash

set -e

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

load_config() {
  local config_dir="${BASEDIR}/configs-old/$1"

  echo "Using config [$1]"

  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -Q \
    -d "${config_dir}" \
    -c "${config_dir}/install.conf.yaml"
}

profile="${BASEDIR}/profiles/${1:-$HOSTNAME}"
if [ ! -f "${profile}" ]; then
  profile="${BASEDIR}/profiles/default"
fi

while IFS= read -r config; do
  load_config "${config}"
done < $profile
