#!/usr/bin/bash

# Start compositor
compton --shadow-exclude argb -b

# Setup the keyboard
xset r rate 200 20
xmodmap ~/.xmodmap

# Start the ssh-agent
eval $(ssh-agent)

# Set the background
feh --bg-tile ~/Documents/cat_tile.png

# Start awesome
exec dbus-launch i3
