# prompt customization

ZSH_THEME="agkozak"
AGKOZAK_LEFT_PROMPT_ONLY=1

AGKOZAK_COLORS_USER_HOST="254"
AGKOZAK_COLORS_PATH="109"
AGKOZAK_COLORS_BRANCH_STATUS="244"

CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(git brew)

source $ZSH/oh-my-zsh.sh

# vim keybindings
bindkey -v

# handy scp wrapper for avoiding the weird local-to-local behavior
scp() {
  if grep -q : <(printf %s "$@")
  then
    command scp "$@"
  else
    echo If you really want to use scp to do cp"'"s job, type '`command !!`'.
    return 1
  fi
}

export EDITOR='nvim'

export PATH="$PATH:$HOME/.cargo/bin"

if [ -d "$FZF_HOME" ]; then
  [ -f "$FZF_HOME/shell/completion.zsh" ] && . "$FZF_HOME/shell/completion.zsh"
  [ -f "$FZF_HOME/shell/key-bindings.zsh" ] && . "$FZF_HOME/shell/key-bindings.zsh"
fi

alias luamake=/home/trevor/Source/lua-language-server/3rd/luamake/luamake
