- defaults:
    link:
      relink: true

- link:
    ~/.xmodmap: xmodmap
    ~/.xsession: xsession
    ~/.config/herbstluftwm: config/herbstluftwm
    ~/.config/i3: config/i3
    ~/.config/polybar: config/polybar
    ~/.config/alacritty/host.yml: config/alacritty/host.yml
